import 'package:get_it/get_it.dart';
import 'package:http/http.dart' as http;
import 'package:loteria_app/core/constants/api_settings.dart';
import 'package:loteria_app/core/id_generator/id_generator.dart';
import 'package:loteria_app/core/id_generator/uuid_generator.dart';
import 'package:loteria_app/core/manager/client_manager.dart';
import 'package:loteria_app/features/card/data/datasources/card_local_datasource_impl.dart';
import 'package:loteria_app/features/card/data/datasources/card_remote_datasource_impl.dart';
import 'package:loteria_app/features/card/data/repositories/card_repository_impl.dart';
import 'package:loteria_app/features/card/domain/datasources/card_local_datasource.dart';
import 'package:loteria_app/features/card/domain/datasources/card_remote_datasource.dart';
import 'package:loteria_app/features/card/domain/repositories/card_repository.dart';
import 'package:loteria_app/features/card/domain/usecases/get_cards_by_set.dart';
import 'package:loteria_app/features/card/domain/usecases/update_card.dart';
import 'package:loteria_app/features/card/presentation/bloc/card/card_bloc.dart';
import 'package:loteria_app/features/game/presentation/bloc/deck/deck_bloc.dart';
import 'package:loteria_app/app/bloc/navigation/navigation_bloc.dart';
import 'package:loteria_app/features/game/presentation/bloc/timer/timer_bloc.dart';
import 'package:loteria_app/features/set/data/datasources/set_local_datasource_impl.dart';
import 'package:loteria_app/features/set/data/datasources/set_remote_datasource_impl.dart';
import 'package:loteria_app/features/set/data/repositories/set_repository_impl.dart';
import 'package:loteria_app/features/set/domain/datasources/set_local_datasource.dart';
import 'package:loteria_app/features/set/domain/datasources/set_remote_datasource.dart';
import 'package:loteria_app/features/set/domain/repositories/set_repository.dart';
import 'package:loteria_app/features/set/domain/usecases/get_all_sets.dart';
import 'package:loteria_app/features/set/domain/usecases/get_sets_with_cards.dart';
import 'package:loteria_app/sync/data/datasources/sync_queue_datasource_impl.dart';
import 'package:loteria_app/sync/data/repositories/sync_repository_impl.dart';
import 'package:loteria_app/sync/domain/datasources/sync_queue_datasource.dart';
import 'package:loteria_app/sync/domain/repositories/sync_repository.dart';
import 'package:loteria_app/sync/domain/usecases/sync_all.dart';
import 'package:uuid/uuid.dart';

import 'features/set/presentation/bloc/set/set_bloc.dart';

part 'init_dependencies.main.dart';