name: App Keep Alive

on:
  schedule:
    - cron: "0 9 */3 * *" # cada 3 días
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    environment: env
    steps:
      - name: Ping Supabase
        run: |
          for i in {1..30}
          do
            echo "Request #$i"
            curl "${{ secrets.API_SUPABASE_URL }}/rest/v1/cards?select=id&limit=1" \
            -H "apikey: ${{ secrets.API_KEY }}" \
            -H "Authorization: Bearer ${{ secrets.API_KEY }}"
            
            sleep 2
          done